name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: prep
        name: Determine most recent snapshot
        run: |
          printf "::set-output name=snapshot::%s" "$PWD/"
          find lts/ -type f | sort --reverse --version-sort | head -n 1

      - name: Checkout example project
        uses: actions/checkout@v3
        with:
          repository: freckle/megarepo
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
          path: test/megarepo

      - name: Update example project resolver
        run: |
          sed -i -E 's%^(resolver: *)([^ ]+)(.*)$%\1${{ steps.prep.outputs.snapshot }}\3%' stack.yaml
        working-directory: test/megarepo/backend

      - uses: freckle/stack-cache-action@v2
        with:
          working-directory: test/megarepo/backend

      - uses: freckle/stack-action@v3
        with:
          working-directory: test/megarepo/backend
          test: false

      - run: make update.post
        working-directory: test/megarepo/backend

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: prep
        run: |
          printf "::set-output name=snapshot::%s" "$PWD/"
          find lts/ -type f | sort --reverse --version-sort | head -n 1

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: freckle/stack-lint-extra-deps
          latest: true
          fileName: stack-lint-extra-deps-x86_64-linux.tar.gz

      - name: Extract
        run: tar -xzf stack-lint-extra-deps-x86_64-linux.tar.gz

      - name: Lint ${{ steps.prep.outputs.snapshot }}
        run: |
          ./stack-lint-extra-deps/stack-lint-extra-deps \
            --color always \
            --exclude '*/amazonka' \
            --exclude 'weeder' \
            --exclude 'algebraic-graphs' \
            --path ${{ steps.prep.outputs.snapshot }}
