name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test

    steps:
      - uses: actions/checkout@v2
      - id: prep
        run: |
          printf "::set-output name=snapshot::"
          find ../lts/ -type f | sort --reverse --version-sort | head -n 1

      - name: Setup
        run: |
          m4 -D RESOLVER=${{ steps.prep.outputs.snapshot }} \
            < stack.yaml.in > stack.yaml

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ./test/.stack-work
          key: ${{ steps.prep.outputs.snapshot }}-${{ hashFiles('test/*.yaml') }}
          restore-keys: |
            ${{ steps.prep.outputs.snapshot }}-

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          stack --no-terminal setup
          stack --no-terminal build --dependencies-only
          stack --no-terminal install --copy-compiler-tool \
            apply-refact \
            dhall \
            fast-tags \
            hlint \
            brittany \
            weeder

          # NOTE: stylish-haskell is broken on lts-19.0 / ghc-9.0. Bring it back
          # when we get to ghc-9.2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: prep
        run: |
          printf "::set-output name=snapshot::"
          find lts/ -type f | sort --reverse --version-sort | head -n 1

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: freckle/stack-lint-extra-deps
          latest: true
          fileName: stack-lint-extra-deps-x86_64-linux.tar.gz

      - name: Extract
        run: tar -xzf stack-lint-extra-deps-x86_64-linux.tar.gz

      - name: Lint ${{ steps.prep.outputs.snapshot }}
        run: |
          ./stack-lint-extra-deps/stack-lint-extra-deps \
            --color always \
            --exclude '*/amazonka' \
            --exclude 'weeder' \
            --path ${{ steps.prep.outputs.snapshot }}
